In [16]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

In [17]:
df=pd.read_csv("cleaned_accident_dataset.csv")

In [18]:
df.head()

,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,road_type,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,highway,...,low,32,high,weather,fatal,2,2,0,no festival,0.85
1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,urban,...,high,34,low,weather,major,4,3,0,no festival,0.10
2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,urban,...,low,21,medium,weather,minor,1,1,0,no festival,0.45
3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,urban,...,low,30,high,distraction,minor,5,2,0,no festival,0.65
4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,highway,...,high,24,low,distraction,minor,2,1,0,no festival,0.10

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

In [20]:
df.head()

,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,road_type,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,7,2,18.680827,73.930388,659,19,5,3,1,0,...,1,32,0,4,0,2,2,0,4,0.85
1,6,2,18.817732,72.790846,505,18,4,3,1,2,...,0,34,1,4,1,4,3,0,4,0.10
2,6,2,19.096889,72.819424,921,4,13,6,0,2,...,1,21,2,4,2,1,1,0,4,0.45
3,1,3,30.787805,76.847507,1184,2,11,3,1,2,...,1,30,0,0,2,5,2,0,4,0.65
4,2,4,12.965155,80.283313,754,7,16,4,0,0,...,0,24,1,0,2,2,1,0,4,0.10

In [23]:
X = df.drop(["risk_score", "accident_severity"], axis=1)
y = df["risk_score"]

In [24]:
x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
model = RandomForestRegressor()

In [26]:
model.fit(x_train,y_train)

RandomForestRegressor()

In [27]:
y_pred = model.predict(x_test)

In [28]:
import numpy as np 

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R² Score:", r2)

Mean Absolute Error (MAE): 4.7500000003502436e-05
Mean Squared Error (MSE): 2.806000000000004e-06
Root Mean Squared Error (RMSE): 0.0016751119365582719
R² Score: 0.9999395922648081

In [29]:
import joblib

joblib.dump(model, "risk_model")

print("Model saved successfully!")

Model saved successfully!